#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileGaps.Logfox.JourneyWebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test2")]
	public partial class JourneyDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public JourneyDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ix01ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JourneyDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JourneyDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JourneyDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JourneyDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_leg_add")]
		public int AddLeg([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> journey_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> leg_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement leg_xml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, journey_id, leg_id, leg_xml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_journey_get")]
		public int GetJourney([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> journey_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] ref System.Xml.Linq.XElement journey_xml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, journey_id, journey_xml);
			journey_xml = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_journey_list")]
		public int GetJourneyList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] ref System.Xml.Linq.XElement journey_xml_list)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, journey_xml_list);
			journey_xml_list = ((System.Xml.Linq.XElement)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_account_add")]
		public int AddAccountOld([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string gigya_uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string device_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string country_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> account_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gigya_uid, email, user_password, device_id, country_code, account_id);
			account_id = ((System.Nullable<System.Guid>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_account_add")]
		public int AddAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string gigya_uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string device_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> country_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string gigya_login_provider, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string nick_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string name_first, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string name_last, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string country_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> account_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gigya_uid, email, user_password, device_id, country_code, gigya_login_provider, nick_name, name_first, name_last, city, country_name, account_id);
			account_id = ((System.Nullable<System.Guid>)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_account_get")]
		public int GetAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string gigya_uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> account_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gigya_uid, email, user_password, account_id);
			account_id = ((System.Nullable<System.Guid>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
